"""Regenerates the symbol map, the ABI constants and the AOT C source.

Usage (from the repository root):

    python -m tools.bftool.gen            # regenerate
    python -m tools.bftool.gen --check    # fail when generated files are stale

Inputs:  brainfuck/programs.json, brainfuck/src/*.bf (hand written, checked
         by tools/bftool/lint.py), brainfuck/constants.txt
Outputs: brainfuck/generated/MEMORY_MAP.md,
         app/src/main/cpp/generated/bf_programs.generated.c, bf_abi.h, BfAbi.java

Copied from ThreadsHideAds (tools/bftool/gen.py at 358373d) and adapted to
TwitterHideAds: stateless programs only (no persistent region), BfAbi lives in
the module package.
"""

import argparse
import json
import os
import re
import sys

if __package__ in (None, ""):
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    __package__ = "bftool"

from . import ir, lint  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MANIFEST = os.path.join(ROOT, "brainfuck", "programs.json")
BF_DIR = os.path.join(ROOT, "brainfuck", "generated")
C_OUT = os.path.join(ROOT, "app", "src", "main", "cpp", "generated", "bf_programs.generated.c")
C_ABI = os.path.join(ROOT, "app", "src", "main", "cpp", "generated", "bf_abi.h")
JAVA_ABI = os.path.join(ROOT, "app", "src", "main", "java", "my", "MrxSiN",
                        "twitterhideads", "BfAbi.java")
CONSTANTS = os.path.join(ROOT, "brainfuck", "constants.txt")


def abi_constants(path=CONSTANTS):
    """`const NAME = VALUE` lines, in file order; `#` starts a comment."""
    consts = {}
    with open(path, encoding="utf-8") as f:
        for number, line in enumerate(f, 1):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = re.fullmatch(r"const\s+([A-Z_][A-Z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|[0-9]+)", line)
            if not m or m.group(1) in consts:
                raise SystemExit("%s:%d: bad constant line" % (path, number))
            consts[m.group(1)] = int(m.group(2), 0)
    return consts


def emit_abi(consts):
    names = list(consts)
    java = [
        "package my.MrxSiN.twitterhideads;",
        "",
        "/** Generated by tools/bftool/gen.py from brainfuck/constants.txt. Do not edit. */",
        "final class BfAbi {",
        "",
        "    private BfAbi() {",
        "    }",
        "",
    ]
    def java_int(v):
        return "0x%X" % v if v > 0x7FFFFFFF else str(v)

    java += ["    static final int %s = %s;" % (n, java_int(consts[n])) for n in names]
    java += ["}", ""]
    c = [
        "/* Generated by tools/bftool/gen.py from brainfuck/constants.txt. Do not edit. */",
        "#ifndef TWITTERHIDEADS_BF_ABI_H",
        "#define TWITTERHIDEADS_BF_ABI_H",
        "",
    ]
    c += ["#define BF_%s %d%s" % (n, consts[n], "u" if consts[n] > 0x7FFFFFFF else "") for n in names]
    c += ["", "#endif", ""]
    return "\n".join(java), "\n".join(c)


def load_manifest(path=MANIFEST):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def generate(manifest_path=MANIFEST):
    """Returns {path: text} for every generated file."""
    manifest = load_manifest(manifest_path)
    base = os.path.dirname(manifest_path)
    files = {}
    c_parts = [
        "/* Generated by tools/bftool/gen.py from brainfuck/src. Do not edit. */",
        "#include \"../bf_runtime.h\"",
        "",
    ]
    table = []
    summary = {"programs": []}
    for index, entry in enumerate(manifest["programs"]):
        if entry["id"] != index:
            raise SystemExit("programs.json ids must be 0..n-1 in order")
        name = entry["name"]
        code, symbols, high_water = load_program(os.path.join(base, entry["source"]), entry)
        ops = ir.compile_bf(code, zero_from=0)
        if not ir.is_static(ops):
            raise SystemExit("%s: generated BF must keep every loop balanced" % name)
        c_parts.append(ir.emit_c(ops, name, entry["tape"]))
        table.append('    {"%s", bf_prog_%s, %d},' % (name, name, entry["tape"]))
        summary["programs"].append({
            "id": index,
            "name": name,
            "tape": entry["tape"],
            "source": entry["source"],
            "bf_commands": len(code),
            "ir_ops": ir.count_ops(ops),
            "scratch_high_water": high_water,
            "symbols": [{"region": r, "name": n, "addr": a, "size": s}
                        for r, n, a, s in symbols],
        })
    c_parts.append("const bf_program_info bf_programs[] = {")
    c_parts.extend(table)
    c_parts.append("};")
    c_parts.append("const int bf_program_count = %d;" % len(table))
    c_parts.append("")
    files[C_OUT] = "\n".join(c_parts)
    files[os.path.join(BF_DIR, "MEMORY_MAP.md")] = memory_map(summary)
    if manifest_path == MANIFEST:
        files[JAVA_ABI], files[C_ABI] = emit_abi(abi_constants())
    return files


def load_program(path, entry):
    """(code, symbols, high water) of one hand-written `.bf` source, which is
    only checked (tools/bftool/lint.py), never rewritten."""
    with open(path, encoding="utf-8") as f:
        src = lint.lint(f.read(), entry["tape"], entry["source"])
    symbols = [("cell", n, a, size) for n, (a, size) in src.cells.items()]
    return src.code, symbols, src.high_water + 1


def program_code(name, manifest_path=MANIFEST):
    """The canonical commands of a program, for the reference interpreter."""
    manifest = load_manifest(manifest_path)
    base = os.path.dirname(manifest_path)
    for entry in manifest["programs"]:
        if entry["name"] == name:
            return load_program(os.path.join(base, entry["source"]), entry)[0]
    raise KeyError(name)


def memory_map(summary):
    """Tape layout of every program, from the assembler's symbol table."""
    out = ["# Brainfuck memory map (generated)", "",
           "Generated by tools/bftool/gen.py from the `%cell` declarations. Do not edit; see docs/BRAINFUCK_ARCHITECTURE.md.", ""]
    for p in summary["programs"]:
        out.append("## %s (program %d)" % (p["name"], p["id"]))
        out.append("")
        out.append("Tape %d cells, zeroed before every request; high-water %d; %d BF commands; %d IR ops."
                   % (p["tape"], p["scratch_high_water"], p["bf_commands"], p["ir_ops"]))
        out.append("")
        out.append("| Region | Name | Address | Size |")
        out.append("| --- | --- | --- | --- |")
        for sym in p["symbols"]:
            out.append("| %s | `%s` | %d | %d |" % (sym["region"], sym["name"], sym["addr"], sym["size"]))
        out.append("")
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    files = generate()
    stale = []
    for path, text in sorted(files.items()):
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as f:
                current = f.read()
        if current != text:
            stale.append(os.path.relpath(path, ROOT))
            if not args.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    if args.check:
        if stale:
            print("Generated Brainfuck files are stale; run python tools/bftool/gen.py:")
            for p in stale:
                print("  " + p)
            return 1
        print("Generated Brainfuck files are up to date.")
        return 0
    for p in stale:
        print("wrote " + p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
